
import { GoogleGenAI, Modality } from "@google/genai";

const PROMPT = `Transform the uploaded image into a speculative black and white line drawing. The style should be minimal, conceptual, and thought-provoking. Emphasize abstract forms and ideas inspired by the original image, rather than a literal depiction. The output should be a single, clean line drawing on a white background. Do not include any text or annotations.`;

export const generateSpeculativeDrawing = async (base64ImageData: string, mimeType: string): Promise<string> => {
  // Use a hardcoded API key for demonstration purposes,
  // as process.env.API_KEY is not available in the browser.
  // In a real application, this should be handled via a backend proxy.
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: PROMPT,
          },
        ],
      },
      config: {
          responseModalities: [Modality.IMAGE],
      },
    });

    if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
              return part.inlineData.data;
            }
        }
    }
    
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new Error('The AI model failed to generate an image.');
  }
};
